---
# Install and setup nginx
# http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html

- name: Updating apt cache and installing python
  apt: name=python state=latest update_cache=yes

- name: Installing pip
  apt: name=python-pip state=latest

- name: Installing python-dev
  apt: name=python-dev state=latest

- name: Installing virtualenv
  pip: name=virtualenv

- name: Installing django
  pip: name=django

- name: Setting up a django project
  shell: django-admin.py startproject mysite

- name: Installing uwsgi
  pip: name=uwsgi

- name: Setting up uwsgi_params
  copy: src=uwsgi_params dest=/home/vagrant/mysite

- name: Installing nginx
  apt: name=nginx state=latest

- name: Setting up mysite_nginx.conf
  copy: src=mysite_nginx.conf dest=/home/vagrant/mysite

- name: Linking mysite_nginx.conf
  file: src=/home/vagrant/mysite/mysite_nginx.conf
        dest=/etc/nginx/sites-enabled/mysite_nginx.conf state=link

- name: Editing settings.py
  shell: echo 'STATIC_ROOT = os.path.join(BASE_DIR, "static/")' >> /home/vagrant/mysite/mysite/settings.py

- name: Running collectstatic
  django_manage: command=collectstatic app_path=/home/vagrant/mysite

- name: Setting up test.py
  copy: src=test.py dest=/home/vagrant/mysite

- name: Setting up mysite_uwsgi.ini
  copy: src=mysite_uwsgi.ini dest=/home/vagrant/mysite

- name: Start nginx
  service: name=nginx state=restarted

# Setup emperor mode
# # create a directory for the vassals
# sudo mkdir /etc/uwsgi
# sudo mkdir /etc/uwsgi/vassals
# # symlink from the default config directory to your config file
# sudo ln -s /path/to/your/mysite/mysite_uwsgi.ini /etc/uwsgi/vassals/
# # run the emperor
# sudo uwsgi --emperor /etc/uwsgi/vassals --uid root --gid root
